module.exports={
    database:{
        dbName:'animal_crossing',
        user:'root',
        password:'YANYAN1113',
        port:3306,
        host:'62.234.172.175'
    },
    security:{
        secretKey:'abcdef',
        expiresIn:60*60*24*30
    },
    categorys:{
        fish:1,
        insects:2,
        villagers:3
    }
}